import type { ReaderTheme } from './types'

/**
 * 内置主题。
 *
 * 加一套主题就是往这个数组里加一条：apply.ts 会把它拼进生成的样式表，
 * data-theme 一切换就生效，不需要动任何组件，也不需要改 CSS。
 * 想要更细的调整（背景图、特殊字体）用设置里的「自定义 CSS」，那是留给你自己的逃生口。
 *
 * 正文色不用纯黑或纯白：长时间阅读纯黑底纯白字最累眼，
 * 所以暗色主题的 readerFg 都压到 0.8 左右的亮度。
 */
export const BUILTIN_THEMES: ReaderTheme[] = [
  {
    id: 'day',
    name: '日间',
    scheme: 'light',
    builtin: true,
    tokens: {
      bg: '#FFFFFF',
      surface: '#F7F7F8',
      surface2: '#EFF0F2',
      border: '#E4E5E9',
      borderStrong: '#D3D6DC',
      fg: '#1F2328',
      fgMuted: '#6B7280',
      fgFaint: '#9AA3B2',
      accent: '#2F6FEB',
      accentSoft: '#EAF1FF',
      danger: '#B42318',
      overlay: 'rgba(17, 19, 23, 0.45)',
      readerBg: '#FFFFFF',
      readerFg: '#23262B',
      readerFgMuted: '#6B7280',
      readerLink: '#2F6FEB',
      readerSelection: '#CFE0FF',
      readerRule: '#E4E5E9',
    },
  },
  {
    id: 'sepia',
    name: '羊皮',
    scheme: 'light',
    builtin: true,
    tokens: {
      bg: '#F6EFE1',
      surface: '#FBF6EC',
      surface2: '#EFE6D4',
      border: '#E0D3BB',
      borderStrong: '#CDBB9C',
      fg: '#3B3227',
      fgMuted: '#7A6A55',
      fgFaint: '#A2917A',
      accent: '#A6603A',
      accentSoft: '#F0E2D2',
      danger: '#A6342A',
      overlay: 'rgba(59, 50, 39, 0.45)',
      readerBg: '#F6EFE1',
      readerFg: '#3B3227',
      readerFgMuted: '#7A6A55',
      readerLink: '#96603A',
      readerSelection: '#E6D4B4',
      readerRule: '#E0D3BB',
    },
  },
  {
    id: 'green',
    name: '护眼',
    scheme: 'light',
    builtin: true,
    tokens: {
      bg: '#E9F2E6',
      surface: '#F2F7F0',
      surface2: '#DDE9D9',
      border: '#CBDCC6',
      borderStrong: '#B2C9AC',
      fg: '#26332A',
      fgMuted: '#5C7061',
      fgFaint: '#8AA08E',
      accent: '#3E7A4E',
      accentSoft: '#D9EBD9',
      danger: '#A63B33',
      overlay: 'rgba(38, 51, 42, 0.42)',
      readerBg: '#E9F2E6',
      readerFg: '#26332A',
      readerFgMuted: '#5C7061',
      readerLink: '#356B45',
      readerSelection: '#C9E0C2',
      readerRule: '#CBDCC6',
    },
  },
  {
    id: 'dusk',
    name: '晨雾',
    scheme: 'light',
    builtin: true,
    tokens: {
      bg: '#EDF1F6',
      surface: '#F5F8FB',
      surface2: '#E1E8F0',
      border: '#D2DBE6',
      borderStrong: '#B7C4D4',
      fg: '#23303F',
      fgMuted: '#5A6B7E',
      fgFaint: '#8896A6',
      accent: '#3D6FA8',
      accentSoft: '#DCE8F5',
      danger: '#AF3A34',
      overlay: 'rgba(35, 48, 63, 0.42)',
      readerBg: '#EDF1F6',
      readerFg: '#23303F',
      readerFgMuted: '#5A6B7E',
      readerLink: '#35679F',
      readerSelection: '#CFE0F2',
      readerRule: '#D2DBE6',
    },
  },
  {
    id: 'night',
    name: '夜间',
    scheme: 'dark',
    builtin: true,
    tokens: {
      bg: '#16181D',
      surface: '#1E2127',
      surface2: '#262A31',
      border: '#31363F',
      borderStrong: '#434A55',
      fg: '#E6E8EC',
      fgMuted: '#9BA3AE',
      fgFaint: '#6E7681',
      accent: '#6E9BF5',
      accentSoft: '#232D3F',
      danger: '#E5716A',
      overlay: 'rgba(0, 0, 0, 0.6)',
      readerBg: '#16181D',
      readerFg: '#C9CDD4',
      readerFgMuted: '#8A929C',
      readerLink: '#7BA6F7',
      readerSelection: '#33405A',
      readerRule: '#31363F',
    },
  },
  {
    id: 'forest',
    name: '深林',
    scheme: 'dark',
    builtin: true,
    tokens: {
      bg: '#131A17',
      surface: '#1A231E',
      surface2: '#222D27',
      border: '#2C3931',
      borderStrong: '#3D4D43',
      fg: '#E2E8E3',
      fgMuted: '#97A69B',
      fgFaint: '#6B7A6F',
      accent: '#6FBB8A',
      accentSoft: '#1E2C24',
      danger: '#E0796F',
      overlay: 'rgba(0, 0, 0, 0.6)',
      readerBg: '#131A17',
      readerFg: '#C4CFC6',
      readerFgMuted: '#86968B',
      readerLink: '#7CC194',
      readerSelection: '#2C4434',
      readerRule: '#2C3931',
    },
  },
  /**
   * 下面两套是「编辑器」形态：外壳换成代码编辑器，正文按代码排版。
   * 颜色不是调的，是抄的——暗色取自 VS Code 的 Dark Modern（编辑器 #1F1F1F、
   * 侧栏 #181818、焦点 #0078D4），语法色取自 Dark+ 的 token 配色；
   * 亮色对应 Light Modern 与 Light+。
   * 抄而不是调，是因为这套主题要的就是「一眼看上去是那个编辑器」，
   * 手一调就不是了。
   */
  {
    id: 'vscode',
    name: 'VS Code 暗',
    scheme: 'dark',
    builtin: true,
    chrome: 'code',
    preset: {
      fontFamily: 'mono',
      fontSize: 15,
      lineHeight: 1.7,
      letterSpacing: 0,
      paragraphGap: 0,
      indent: 0,
      contentWidth: 56,
      align: 'left',
    },
    tokens: {
      bg: '#1F1F1F',
      surface: '#181818',
      surface2: '#2B2B2B',
      border: '#2B2B2B',
      borderStrong: '#3C3C3C',
      fg: '#CCCCCC',
      fgMuted: '#9D9D9D',
      fgFaint: '#868686',
      accent: '#0078D4',
      accentSoft: '#04395E',
      danger: '#F14C4C',
      overlay: 'rgba(0, 0, 0, 0.55)',
      readerBg: '#1F1F1F',
      readerFg: '#CCCCCC',
      readerFgMuted: '#9D9D9D',
      readerLink: '#4E94CE',
      readerSelection: '#264F78',
      readerRule: '#2B2B2B',
    },
    code: {
      gutter: '#6E7681',
      guide: '#404040',
      string: '#CE9178',
      comment: '#6A9955',
      keyword: '#569CD6',
      number: '#B5CEA8',
      type: '#4EC9B0',
      fn: '#DCDCAA',
      prop: '#9CDCFE',
      image: '#4E94CE',
    },
  },
  {
    id: 'vscode-light',
    name: 'VS Code 亮',
    scheme: 'light',
    builtin: true,
    chrome: 'code',
    preset: {
      fontFamily: 'mono',
      fontSize: 15,
      lineHeight: 1.7,
      letterSpacing: 0,
      paragraphGap: 0,
      indent: 0,
      contentWidth: 56,
      align: 'left',
    },
    tokens: {
      bg: '#FFFFFF',
      surface: '#F8F8F8',
      surface2: '#E5E5E5',
      border: '#E5E5E5',
      borderStrong: '#CECECE',
      fg: '#3B3B3B',
      fgMuted: '#616161',
      fgFaint: '#868686',
      accent: '#005FB8',
      accentSoft: '#E8F0FB',
      danger: '#CD3131',
      overlay: 'rgba(0, 0, 0, 0.35)',
      readerBg: '#FFFFFF',
      readerFg: '#3B3B3B',
      readerFgMuted: '#616161',
      readerLink: '#006AB1',
      readerSelection: '#ADD6FF',
      readerRule: '#E5E5E5',
    },
    code: {
      gutter: '#6E7681',
      guide: '#D3D3D3',
      string: '#A31515',
      comment: '#008000',
      keyword: '#0000FF',
      number: '#098658',
      type: '#267F99',
      fn: '#795E26',
      prop: '#001080',
      image: '#006AB1',
    },
  },
  /**
   * 下面十套是「伪装成别的办公软件」的主题，和 VS Code 那两套同一个路子：
   * 颜色是抄的，不是调的。
   *
   *   doc   飞书文档   主蓝 #3370FF，中性色 #1F2329 / #646A73 / #8F959E / #F5F6F7
   *   chat  企业微信   按桌面版截图量的：功能栏 #DBE9F7（淡蓝，选中那格 #C9DEF7 垫底）、
   *                    会话列表 #F0F3F7、聊天底 #F5F7FA、收到的气泡 #E4E7EB、
   *                    链接与选中态 #267EF0、选中的会话行 #3586F4、未读角标 #FC5A4E
   *   page  Word       Office 品牌蓝 #185ABD
   *   sheet Excel      Office 品牌绿 #107C41（页签、按钮、开始屏幕的那个绿按钮）；
   *                    但**网格里的选中框是另一个绿** #217346——Excel 从 2007 起
   *                    就用它画选中的行列标题和单元格框，见下面 sheet 那一层
   *   slide PowerPoint Office 品牌橙 #C43E1C
   *
   * Office 那三套的中性色不是挑的，是 Fluent 2 的官方 token（桌面版 Word / Excel /
   * PowerPoint 与 Office 网页版共用这一套）：亮色 #FFFFFF / #F5F5F5 / #F0F0F0 /
   * #E0E0E0 / #D1D1D1 / #242424 / #616161，深色 #1F1F1F / #141414 / #292929 /
   * #3D3D3D / #525252 / #FFFFFF / #D6D6D6 / #ADADAD；品牌的暗色版本是同一个色相
   * 抬到 60% 亮度（见 docs/SPEC.md 决定记录 26）。
   *
   * 每套亮色都配一套暗色，配色不是把亮色反过来，而是照着各家自己的深色模式来：
   * 「飞书 暗」是文档页比外壳略亮，「Word 暗」的页面是深灰的纸（不是白纸），
   * 「PPT 暗」连幻灯片一起压暗——不然暗色主题里会有一块刺眼的白板。
   */
  {
    id: 'feishu',
    name: '飞书 亮',
    scheme: 'light',
    builtin: true,
    chrome: 'doc',
    preset: {
      fontFamily: 'sans',
      fontSize: 17,
      lineHeight: 1.7,
      letterSpacing: 0,
      paragraphGap: 0.6,
      indent: 0,
      contentWidth: 46,
      align: 'left',
    },
    tokens: {
      bg: '#F5F6F7',
      surface: '#FFFFFF',
      surface2: '#EFF0F1',
      border: '#DEE0E3',
      borderStrong: '#C9CCD0',
      fg: '#1F2329',
      fgMuted: '#646A73',
      fgFaint: '#8F959E',
      accent: '#3370FF',
      accentSoft: '#E1EAFF',
      danger: '#D83931',
      overlay: 'rgba(31, 35, 41, 0.5)',
      readerBg: '#FFFFFF',
      readerFg: '#1F2329',
      readerFgMuted: '#646A73',
      readerLink: '#3370FF',
      readerSelection: '#CEDDFF',
      readerRule: '#DEE0E3',
    },
  },
  {
    id: 'feishu-dark',
    name: '飞书 暗',
    scheme: 'dark',
    builtin: true,
    chrome: 'doc',
    preset: {
      fontFamily: 'sans',
      fontSize: 17,
      lineHeight: 1.7,
      letterSpacing: 0,
      paragraphGap: 0.6,
      indent: 0,
      contentWidth: 46,
      align: 'left',
    },
    tokens: {
      bg: '#17181A',
      surface: '#1F2124',
      surface2: '#2A2D31',
      border: '#34383D',
      borderStrong: '#454A50',
      fg: '#E8E9EA',
      fgMuted: '#A6A9AD',
      fgFaint: '#7A7E83',
      accent: '#4E83FD',
      accentSoft: '#23304C',
      danger: '#F0554D',
      overlay: 'rgba(0, 0, 0, 0.6)',
      readerBg: '#1F2124',
      readerFg: '#DADCE0',
      readerFgMuted: '#9CA0A6',
      readerLink: '#7CA5FF',
      readerSelection: '#2D3E65',
      readerRule: '#34383D',
    },
  },
  {
    id: 'wecom',
    name: '企业微信 亮',
    scheme: 'light',
    builtin: true,
    chrome: 'chat',
    preset: {
      fontFamily: 'sans',
      fontSize: 16,
      lineHeight: 1.65,
      letterSpacing: 0,
      paragraphGap: 0.5,
      indent: 0,
      contentWidth: 44,
      align: 'left',
    },
    tokens: {
      bg: '#F5F7FA',
      surface: '#FFFFFF',
      surface2: '#F0F3F7',
      border: '#E5E8EC',
      borderStrong: '#D5DAE0',
      fg: '#10141A',
      fgMuted: '#6D7176',
      fgFaint: '#9DA0A3',
      accent: '#267EF0',
      accentSoft: '#E1F0FE',
      danger: '#FC5A4E',
      overlay: 'rgba(16, 20, 26, 0.5)',
      readerBg: '#F5F7FA',
      readerFg: '#10141A',
      readerFgMuted: '#6D7176',
      readerLink: '#267EF0',
      readerSelection: 'rgba(38, 126, 240, 0.22)',
      readerRule: '#E5E8EC',
    },
    chat: {
      rail: '#DBE9F7',
      railFg: '#7C8B9D',
      railTile: '#C9DEF7',
      railActive: '#267EF0',
      select: '#3586F4',
      bubble: '#E4E7EB',
    },
  },
  {
    id: 'wecom-dark',
    name: '企业微信 暗',
    scheme: 'dark',
    builtin: true,
    chrome: 'chat',
    preset: {
      fontFamily: 'sans',
      fontSize: 16,
      lineHeight: 1.65,
      letterSpacing: 0,
      paragraphGap: 0.5,
      indent: 0,
      contentWidth: 44,
      align: 'left',
    },
    tokens: {
      bg: '#171A1F',
      surface: '#212429',
      surface2: '#1D2025',
      border: '#2B2F35',
      borderStrong: '#3A3F47',
      fg: '#E6E8EA',
      fgMuted: '#9BA1A8',
      fgFaint: '#6E747B',
      accent: '#4C9DF5',
      accentSoft: '#1D2C3E',
      danger: '#FF6B5E',
      overlay: 'rgba(0, 0, 0, 0.6)',
      readerBg: '#171A1F',
      readerFg: '#DDE0E3',
      readerFgMuted: '#9BA1A8',
      readerLink: '#6FB0F5',
      readerSelection: 'rgba(76, 157, 245, 0.26)',
      readerRule: '#2B2F35',
    },
    chat: {
      rail: '#1E2228',
      railFg: '#8B929B',
      railTile: '#2C333C',
      railActive: '#58A6F7',
      select: '#2F6FD0',
      bubble: '#262A30',
    },
  },
  {
    id: 'word',
    name: 'Word 亮',
    scheme: 'light',
    builtin: true,
    chrome: 'page',
    preset: {
      fontFamily: 'serif',
      fontSize: 16,
      lineHeight: 1.5,
      letterSpacing: 0,
      paragraphGap: 0,
      indent: 2,
      contentWidth: 42,
      align: 'left',
    },
    tokens: {
      // 桌面（纸外面那一圈）是 #E5EBEF——2026-09-24 按截图重量的，不是 Fluent 的中性灰。
      // 标题栏用的是同一个值：Word 里标题栏和桌面本来就是一片
      bg: '#E5EBEF',
      surface: '#FFFFFF',
      surface2: '#F5F5F5',
      border: '#E0E0E0',
      borderStrong: '#D1D1D1',
      fg: '#242424',
      fgMuted: '#616161',
      fgFaint: '#8F8F8F',
      accent: '#185ABD',
      accentSoft: '#E8EFF8',
      danger: '#C42B1C',
      overlay: 'rgba(0, 0, 0, 0.4)',
      readerBg: '#FFFFFF',
      readerFg: '#202020',
      readerFgMuted: '#616161',
      readerLink: '#0563C1',
      readerSelection: '#B4D5FE',
      readerRule: '#E0E0E0',
    },
    page: {
      paperEdge: '#C6C6C6',
      crop: '#AAAAAA',
      control: '#8A8A8A',
      field: '#FAFAFA',
    },
  },
  {
    id: 'word-dark',
    name: 'Word 暗',
    scheme: 'dark',
    builtin: true,
    chrome: 'page',
    preset: {
      fontFamily: 'serif',
      fontSize: 16,
      lineHeight: 1.5,
      letterSpacing: 0,
      paragraphGap: 0,
      indent: 2,
      contentWidth: 42,
      align: 'left',
    },
    tokens: {
      bg: '#141414',
      surface: '#1F1F1F',
      surface2: '#292929',
      border: '#333333',
      borderStrong: '#4D4D4D',
      fg: '#FFFFFF',
      fgMuted: '#D6D6D6',
      fgFaint: '#ADADAD',
      accent: '#568CDC',
      accentSoft: '#232D3C',
      danger: '#F1707B',
      overlay: 'rgba(0, 0, 0, 0.6)',
      readerBg: '#262626',
      readerFg: '#E0E0E0',
      readerFgMuted: '#A0A0A0',
      readerLink: '#3D99F5',
      readerSelection: '#37465D',
      readerRule: '#333333',
    },
    page: {
      paperEdge: '#3D3D3D',
      crop: '#525252',
      control: '#6E6E6E',
      field: '#292929',
    },
  },
  {
    id: 'excel',
    name: 'Excel 亮',
    scheme: 'light',
    builtin: true,
    chrome: 'sheet',
    preset: {
      fontFamily: 'sans',
      fontSize: 14,
      lineHeight: 1.45,
      letterSpacing: 0,
      paragraphGap: 0,
      indent: 0,
      contentWidth: 64,
      align: 'left',
    },
    tokens: {
      bg: '#FFFFFF',
      surface: '#FFFFFF',
      surface2: '#F5F5F5',
      border: '#E1E1E1',
      borderStrong: '#C8C8C8',
      fg: '#242424',
      fgMuted: '#616161',
      fgFaint: '#8F8F8F',
      accent: '#107C41',
      accentSoft: '#E7F2EC',
      danger: '#C42B1C',
      overlay: 'rgba(0, 0, 0, 0.4)',
      readerBg: '#FFFFFF',
      readerFg: '#242424',
      readerFgMuted: '#616161',
      readerLink: '#0563C1',
      readerSelection: '#CFE5D9',
      readerRule: '#E1E1E1',
    },
    /*
     * 网格这一层的值：2026-09-24 按一张 1917×1006 的 Excel 截图量的
     * （那张图右上角写着工作簿1 - Excel，功能区里挂着 OfficePLUS 与两个加载项）。
     *
     *   gridLine    #E0E0E0（量了三条，都是这个值）
     *   headerBg    #F0F0F0，headerFg #444444，headerLine #ABABAB（标题行底下那条）
     *   headerSelBg #E1E1E1：**选中的行列标题是灰的，不是绿的**——绿的只有
     *               「A」/「1」那几个字和朝单元格那一侧的 2px 边（#217346）
     *   select      #217346：Excel 的选中绿。它和品牌绿 #107C41 是两个色，
     *               前者从 Office 2007 用到今天，后者是现在的品牌色（页签、按钮）
     *   chrome      #E4EAEE：标题栏、页签行、工作表标签条、开始屏幕左栏共用这一层
     *               （量出来的；Excel 365 的标题栏不是白的，这两条在 Fluent 里连成一片）
     *   field       #FFFFFF（名称框与编辑栏），control #8A8A8A（下拉框与药丸的描边）
     */
    sheet: {
      gridLine: '#E0E0E0',
      headerBg: '#F0F0F0',
      headerFg: '#444444',
      headerLine: '#ABABAB',
      headerSelBg: '#E1E1E1',
      select: '#217346',
      chrome: '#E4EAEE',
      field: '#FFFFFF',
      control: '#8A8A8A',
    },
  },
  {
    id: 'excel-dark',
    name: 'Excel 暗',
    scheme: 'dark',
    builtin: true,
    chrome: 'sheet',
    preset: {
      fontFamily: 'sans',
      fontSize: 14,
      lineHeight: 1.45,
      letterSpacing: 0,
      paragraphGap: 0,
      indent: 0,
      contentWidth: 64,
      align: 'left',
    },
    tokens: {
      bg: '#1F1F1F',
      surface: '#292929',
      surface2: '#333333',
      border: '#3D3D3D',
      borderStrong: '#525252',
      fg: '#FFFFFF',
      fgMuted: '#D6D6D6',
      fgFaint: '#ADADAD',
      accent: '#51D68E',
      accentSoft: '#294435',
      danger: '#F1707B',
      overlay: 'rgba(0, 0, 0, 0.6)',
      readerBg: '#1F1F1F',
      readerFg: '#D6D6D6',
      readerFgMuted: '#A0A0A0',
      readerLink: '#3D99F5',
      readerSelection: '#2F543F',
      readerRule: '#3D3D3D',
    },
    // 暗色没有截图可量（那张 Excel 截图是亮的），所以照 Excel 自己的深色模式配：
    // 网格线比底深一档、标题底与面板同色、选中框跟着暗色下的强调色走
    sheet: {
      gridLine: '#404040',
      headerBg: '#292929',
      headerFg: '#D6D6D6',
      headerLine: '#525252',
      headerSelBg: '#3D3D3D',
      select: '#51D68E',
      chrome: '#1F1F1F',
      field: '#292929',
      control: '#6E6E6E',
    },
  },
  {
    id: 'ppt',
    name: 'PPT 亮',
    scheme: 'light',
    builtin: true,
    chrome: 'slide',
    preset: {
      fontFamily: 'sans',
      fontSize: 18,
      lineHeight: 1.5,
      letterSpacing: 0,
      paragraphGap: 0.4,
      indent: 0,
      contentWidth: 60,
      align: 'left',
    },
    tokens: {
      bg: '#BFBFBF',
      surface: '#FFFFFF',
      surface2: '#F0F0F0',
      border: '#E0E0E0',
      borderStrong: '#C8C8C8',
      fg: '#242424',
      fgMuted: '#616161',
      fgFaint: '#8F8F8F',
      accent: '#C43E1C',
      accentSoft: '#F9ECE8',
      danger: '#C42B1C',
      overlay: 'rgba(0, 0, 0, 0.45)',
      readerBg: '#FFFFFF',
      readerFg: '#202020',
      readerFgMuted: '#616161',
      readerLink: '#0563C1',
      readerSelection: '#B4D5FE',
      readerRule: '#E0E0E0',
    },
  },
  {
    id: 'ppt-dark',
    name: 'PPT 暗',
    scheme: 'dark',
    builtin: true,
    chrome: 'slide',
    preset: {
      fontFamily: 'sans',
      fontSize: 18,
      lineHeight: 1.5,
      letterSpacing: 0,
      paragraphGap: 0.4,
      indent: 0,
      contentWidth: 60,
      align: 'left',
    },
    tokens: {
      bg: '#0A0A0A',
      surface: '#1F1F1F',
      surface2: '#292929',
      border: '#333333',
      borderStrong: '#4D4D4D',
      fg: '#FFFFFF',
      fgMuted: '#D6D6D6',
      fgFaint: '#ADADAD',
      accent: '#D97359',
      accentSoft: '#34201B',
      danger: '#F1707B',
      overlay: 'rgba(0, 0, 0, 0.65)',
      readerBg: '#1F1F1F',
      readerFg: '#E0E0E0',
      readerFgMuted: '#A0A0A0',
      readerLink: '#3D99F5',
      readerSelection: '#543831',
      readerRule: '#333333',
    },
  },
]
